FROM python:3.12-slim

WORKDIR /app

COPY server_gen_vertex/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY server_gen_vertex/ .

EXPOSE 8002

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]