services:
  server_gen_vertex:
    build:
      context: .
      dockerfile: dockerfile.server_gen_vertex
    container_name: server_gen_vertex
    image: server_gen_vertex
    ports:
      - "8002:8002"
    volumes:
      - ./server_gen_vertex:/app
      - ./server_gen_vertex/gcp-credentials.json:/app/gcp-credentials.json:ro
    environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-credentials.json
    - PYTHONUNBUFFERED=1
  server_build:
    build:
      context: .
      dockerfile: dockerfile.server_build
    container_name: server_build
    image: server_build
    ports:
      - "3000:3000"
    volumes:
      - ./server_build:/app
  client:
    build:
      context: .
      dockerfile: dockerfile.client
    container_name: client
    image: client
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=5
      - PYTHONUNBUFFERED=1
    volumes:
      - ./client:/app