FROM python:3.12-slim

WORKDIR /app

COPY server_gen/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY server_gen/ .

EXPOSE 8002

CMD ["uvicorn", "main:app", "--port", "8002"]